sudo: required
services:
  - docker

before_install:
  - docker build -t 11710461/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 11710461/react-test npm test -- --coverage

after_success:
  - docker build -t 11710461/multi-client ./client
  - docker build -t 11710461/multi-nginx ./nginx
  - docker build -t 11710461/multi-server ./server
  - docker build -t 11710461/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 11710461/multi-client
  - docker push 11710461/multi-nginx
  - docker push 11710461/multi-server
  - docker push 11710461/multi-worker

